version: '2'

services:
  orderer.trackandtrace.com:
    container_name: orderer.trackandtrace.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    volumes:
        - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/trackandtrace.com/orderers/orderer.trackandtrace.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/trackandtrace.com/orderers/orderer.trackandtrace.com/tls:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  # Definieren Sie ähnliche Dienste für die Peers jeder Organisation. Sie können diesen Block kopieren und für jeden Peer anpassen.
  peer0.consignor.trackandtrace.com:
    container_name: peer0.consignor.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.consignor.trackandtrace.com
      - CORE_PEER_ADDRESS=peer0.consignor.trackandtrace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consignor.trackandtrace.com:7051
      - CORE_PEER_LOCALMSPID=ConsignorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/peerOrganizations/consignor.trackandtrace.com/users/Admin@consignor.trackandtrace.com/msp
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/consignor.trackandtrace.com/peers/peer0.consignor.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/consignor.trackandtrace.com/peers/peer0.consignor.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
        - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
        - ./crypto-config/ordererOrganizations/trackandtrace.com/orderers/orderer.trackandtrace.com/msp/tlscacerts:/etc/hyperledger/fabric/orderer
        - ./crypto-config/peerOrganizations/consignor.trackandtrace.com/users/Admin@consignor.trackandtrace.com/msp:/etc/hyperledger/fabric/crypto-config/peerOrganizations/consignor.trackandtrace.com/users/Admin@consignor.trackandtrace.com/msp
    ports:
      - 7051:7051

  peer1.consignor.trackandtrace.com:
    container_name: peer1.consignor.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.consignor.trackandtrace.com
      - CORE_PEER_ADDRESS=peer1.consignor.trackandtrace.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.consignor.trackandtrace.com:7052
      - CORE_PEER_LOCALMSPID=ConsignorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/consignor.trackandtrace.com/peers/peer1.consignor.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/consignor.trackandtrace.com/peers/peer1.consignor.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7052:7052    

  peer0.consignee.trackandtrace.com:
    container_name: peer0.consignee.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.consignee.trackandtrace.com
      - CORE_PEER_ADDRESS=peer0.consignee.trackandtrace.com:7053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consignee.trackandtrace.com:7053
      - CORE_PEER_LOCALMSPID=ConsigneeMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/consignee.trackandtrace.com/peers/peer0.consignee.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/consignee.trackandtrace.com/peers/peer0.consignee.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7053:7053

  peer1.consignee.trackandtrace.com:
    container_name: peer1.consignee.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.consignee.trackandtrace.com
      - CORE_PEER_ADDRESS=peer1.consignee.trackandtrace.com:7054
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.consignee.trackandtrace.com:7054
      - CORE_PEER_LOCALMSPID=ConsigneeMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/consignee.trackandtrace.com/peers/peer1.consignee.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/consignee.trackandtrace.com/peers/peer1.consignee.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7054:7054

  peer0.precarriageshipper.trackandtrace.com:
    container_name: peer0.precarriageshipper.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.precarriageshipper.trackandtrace.com
      - CORE_PEER_ADDRESS=peer0.precarriageshipper.trackandtrace.com:7055
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.precarriageshipper.trackandtrace.com:7055
      - CORE_PEER_LOCALMSPID=PreCarriageShipperMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/precarriageshipper.trackandtrace.com/peers/peer0.precarriageshipper.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/precarriageshipper.trackandtrace.com/peers/peer0.precarriageshipper.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7055:7055

  peer1.precarriageshipper.trackandtrace.com:
    container_name: peer1.precarriageshipper.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.precarriageshipper.trackandtrace.com
      - CORE_PEER_ADDRESS=peer1.precarriageshipper.trackandtrace.com:7056
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.precarriageshipper.trackandtrace.com:7056
      - CORE_PEER_LOCALMSPID=PreCarriageShipperMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/precarriageshipper.trackandtrace.com/peers/peer1.precarriageshipper.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/precarriageshipper.trackandtrace.com/peers/peer1.precarriageshipper.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7056:7056

  peer0.maincarrier.trackandtrace.com:
    container_name: peer0.maincarrier.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.maincarrier.trackandtrace.com
      - CORE_PEER_ADDRESS=peer0.maincarrier.trackandtrace.com:7057
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.maincarrier.trackandtrace.com:7057
      - CORE_PEER_LOCALMSPID=MainCarrierMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/maincarrier.trackandtrace.com/peers/peer0.maincarrier.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/maincarrier.trackandtrace.com/peers/peer0.maincarrier.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7057:7057

  peer1.maincarrier.trackandtrace.com:
    container_name: peer1.maincarrier.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.maincarrier.trackandtrace.com
      - CORE_PEER_ADDRESS=peer1.maincarrier.trackandtrace.com:7058
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.maincarrier.trackandtrace.com:7058
      - CORE_PEER_LOCALMSPID=MainCarrierMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/maincarrier.trackandtrace.com/peers/peer1.maincarrier.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/maincarrier.trackandtrace.com/peers/peer1.maincarrier.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7058:7058

  peer0.oncarriageshipper.trackandtrace.com:
    container_name: peer0.oncarriageshipper.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.oncarriageshipper.trackandtrace.com
      - CORE_PEER_ADDRESS=peer0.oncarriageshipper.trackandtrace.com:7059
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.oncarriageshipper.trackandtrace.com:7059
      - CORE_PEER_LOCALMSPID=OnCarriageShipperMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/oncarriageshipper.trackandtrace.com/peers/peer0.oncarriageshipper.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/oncarriageshipper.trackandtrace.com/peers/peer0.oncarriageshipper.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7059:7059

  peer1.oncarriageshipper.trackandtrace.com:
    container_name: peer1.oncarriageshipper.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.oncarriageshipper.trackandtrace.com
      - CORE_PEER_ADDRESS=peer1.oncarriageshipper.trackandtrace.com:7060
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.oncarriageshipper.trackandtrace.com:7060
      - CORE_PEER_LOCALMSPID=OnCarriageShipperMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/oncarriageshipper.trackandtrace.com/peers/peer1.oncarriageshipper.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/oncarriageshipper.trackandtrace.com/peers/peer1.oncarriageshipper.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7060:7060

  peer0.customs.trackandtrace.com:
    container_name: peer0.customs.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.customs.trackandtrace.com
      - CORE_PEER_ADDRESS=peer0.customs.trackandtrace.com:7061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.customs.trackandtrace.com:7061
      - CORE_PEER_LOCALMSPID=CustomsMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/customs.trackandtrace.com/peers/peer0.customs.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/customs.trackandtrace.com/peers/peer0.customs.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7061:7061

  peer1.customs.trackandtrace.com:
    container_name: peer1.customs.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.customs.trackandtrace.com
      - CORE_PEER_ADDRESS=peer1.customs.trackandtrace.com:7062
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.customs.trackandtrace.com:7062
      - CORE_PEER_LOCALMSPID=CustomsMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/customs.trackandtrace.com/peers/peer1.customs.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/customs.trackandtrace.com/peers/peer1.customs.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7062:7062