version: '2'

services:
  orderer.trackandtrace.com:
    container_name: orderer.trackandtrace.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    volumes:
        - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/trackandtrace.com/orderers/orderer.trackandtrace.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/trackandtrace.com/orderers/orderer.trackandtrace.com/tls:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  # Definieren Sie ähnliche Dienste für die Peers jeder Organisation. Sie können diesen Block kopieren und für jeden Peer anpassen.
  peer0.consignor.trackandtrace.com:
    container_name: peer0.consignor.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.consignor.trackandtrace.com
      - CORE_PEER_ADDRESS=peer0.consignor.trackandtrace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consignor.trackandtrace.com:7051
      - CORE_PEER_LOCALMSPID=ConsignorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/peerOrganizations/consignor.trackandtrace.com/users/Admin@consignor.trackandtrace.com/msp
      - CORE_PEER_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/consignor.trackandtrace.com/peers/peer0.consignor.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/consignor.trackandtrace.com/peers/peer0.consignor.trackandtrace.com/tls/:/etc/hyperledger/fabric/tls
        - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
        - ./crypto-config/ordererOrganizations/trackandtrace.com/orderers/orderer.trackandtrace.com/msp/tlscacerts:/etc/hyperledger/fabric/orderer
        - ./crypto-config/peerOrganizations/consignor.trackandtrace.com/users/Admin@consignor.trackandtrace.com/msp:/etc/hyperledger/fabric/crypto-config/peerOrganizations/consignor.trackandtrace.com/users/Admin@consignor.trackandtrace.com/msp
        - ./consignor:/var/hyperledger/fabric/config
        - ./crypto-config/peerOrganizations/consignor.trackandtrace.com/peers/peer0.consignor.trackandtrace.com/tls:/var/hyperledger/fabric/config/tls
        - ./crypto-config/peerOrganizations/consignor.trackandtrace.com/users/Admin@consignor.trackandtrace.com/tls:/var/hyperledger/fabric/config/users
        - ./chaincode-java:/etc/hyperledger/fabric/chaincode
    ports:
      - 7051:7051


  peer0.consignee.trackandtrace.com:
    container_name: peer0.consignee.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.consignee.trackandtrace.com
      - CORE_PEER_ADDRESS=peer0.consignee.trackandtrace.com:7057
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consignee.trackandtrace.com:7057
      - CORE_PEER_LOCALMSPID=ConsigneeMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/peerOrganizations/consignee.trackandtrace.com/users/Admin@consignee.trackandtrace.com/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/consignee.trackandtrace.com/peers/peer0.consignee.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/consignee.trackandtrace.com/peers/peer0.consignee.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - ./crypto-config/ordererOrganizations/trackandtrace.com/orderers/orderer.trackandtrace.com/msp/tlscacerts:/etc/hyperledger/fabric/orderer
      - ./crypto-config/peerOrganizations/consignee.trackandtrace.com/users/Admin@consignee.trackandtrace.com/msp:/etc/hyperledger/fabric/crypto-config/peerOrganizations/consignee.trackandtrace.com/users/Admin@consignee.trackandtrace.com/msp
      - ./consignee:/var/hyperledger/fabric/config
      - ./crypto-config/peerOrganizations/consignee.trackandtrace.com/peers/peer0.consignee.trackandtrace.com/tls:/var/hyperledger/fabric/config/tls
      - ./crypto-config/peerOrganizations/consignee.trackandtrace.com/users/Admin@consignee.trackandtrace.com/tls:/var/hyperledger/fabric/config/users
      - ./chaincode-java:/etc/hyperledger/fabric/chaincode
    ports:
      - 7057:7057


  peer0.precarriageshipper.trackandtrace.com:
    container_name: peer0.precarriageshipper.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.precarriageshipper.trackandtrace.com
      - CORE_PEER_ADDRESS=peer0.precarriageshipper.trackandtrace.com:7053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.precarriageshipper.trackandtrace.com:7053
      - CORE_PEER_LOCALMSPID=PreCarriageShipperMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/peerOrganizations/precarriageshipper.trackandtrace.com/users/Admin@precarriageshipper.trackandtrace.com/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/precarriageshipper.trackandtrace.com/peers/peer0.precarriageshipper.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/precarriageshipper.trackandtrace.com/peers/peer0.precarriageshipper.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - ./crypto-config/ordererOrganizations/trackandtrace.com/orderers/orderer.trackandtrace.com/msp/tlscacerts:/etc/hyperledger/fabric/orderer
      - ./crypto-config/peerOrganizations/precarriageshipper.trackandtrace.com/users/Admin@precarriageshipper.trackandtrace.com/msp:/etc/hyperledger/fabric/crypto-config/peerOrganizations/precarriageshipper.trackandtrace.com/users/Admin@precarriageshipper.trackandtrace.com/msp
      - ./precarriage:/var/hyperledger/fabric/config
      - ./crypto-config/peerOrganizations/precarriageshipper.trackandtrace.com/peers/peer0.precarriageshipper.trackandtrace.com/tls:/var/hyperledger/fabric/config/tls
      - ./crypto-config/peerOrganizations/precarriageshipper.trackandtrace.com/users/Admin@precarriageshipper.trackandtrace.com/tls:/var/hyperledger/fabric/config/users
      - ./chaincode-java:/etc/hyperledger/fabric/chaincode
    ports:
      - 7053:7053


  peer0.maincarrier.trackandtrace.com:
    container_name: peer0.maincarrier.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.maincarrier.trackandtrace.com
      - CORE_PEER_ADDRESS=peer0.maincarrier.trackandtrace.com:7054
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.maincarrier.trackandtrace.com:7054
      - CORE_PEER_LOCALMSPID=MainCarrierMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/peerOrganizations/maincarrier.trackandtrace.com/users/Admin@maincarrier.trackandtrace.com/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/maincarrier.trackandtrace.com/peers/peer0.maincarrier.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/maincarrier.trackandtrace.com/peers/peer0.maincarrier.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - ./crypto-config/ordererOrganizations/trackandtrace.com/orderers/orderer.trackandtrace.com/msp/tlscacerts:/etc/hyperledger/fabric/orderer
      - ./crypto-config/peerOrganizations/maincarrier.trackandtrace.com/users/Admin@maincarrier.trackandtrace.com/msp:/etc/hyperledger/fabric/crypto-config/peerOrganizations/maincarrier.trackandtrace.com/users/Admin@maincarrier.trackandtrace.com/msp
      - ./maincarrier:/var/hyperledger/fabric/config
      - ./crypto-config/peerOrganizations/maincarrier.trackandtrace.com/peers/peer0.maincarrier.trackandtrace.com/tls:/var/hyperledger/fabric/config/tls
      - ./crypto-config/peerOrganizations/maincarrier.trackandtrace.com/users/Admin@maincarrier.trackandtrace.com/tls:/var/hyperledger/fabric/config/users
      - ./chaincode-java:/etc/hyperledger/fabric/chaincode
    ports:
      - 7054:7054


  peer0.oncarriageshipper.trackandtrace.com:
    container_name: peer0.oncarriageshipper.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.oncarriageshipper.trackandtrace.com
      - CORE_PEER_ADDRESS=peer0.oncarriageshipper.trackandtrace.com:7055
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.oncarriageshipper.trackandtrace.com:7055
      - CORE_PEER_LOCALMSPID=OnCarriageShipperMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/peerOrganizations/oncarriageshipper.trackandtrace.com/users/Admin@oncarriageshipper.trackandtrace.com/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/oncarriageshipper.trackandtrace.com/peers/peer0.oncarriageshipper.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/oncarriageshipper.trackandtrace.com/peers/peer0.oncarriageshipper.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - ./crypto-config/ordererOrganizations/trackandtrace.com/orderers/orderer.trackandtrace.com/msp/tlscacerts:/etc/hyperledger/fabric/orderer
      - ./crypto-config/peerOrganizations/oncarriageshipper.trackandtrace.com/users/Admin@oncarriageshipper.trackandtrace.com/msp:/etc/hyperledger/fabric/crypto-config/peerOrganizations/oncarriageshipper.trackandtrace.com/users/Admin@oncarriageshipper.trackandtrace.com/msp
      - ./oncarriage:/var/hyperledger/fabric/config
      - ./crypto-config/peerOrganizations/oncarriageshipper.trackandtrace.com/peers/peer0.oncarriageshipper.trackandtrace.com/tls/:/var/hyperledger/fabric/config/tls
      - ./crypto-config/peerOrganizations/oncarriageshipper.trackandtrace.com/users/Admin@oncarriageshipper.trackandtrace.com/tls:/var/hyperledger/fabric/config/users
      - ./chaincode-java:/etc/hyperledger/fabric/chaincode
    ports:
      - 7055:7055


  peer0.customs.trackandtrace.com:
    container_name: peer0.customs.trackandtrace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.customs.trackandtrace.com
      - CORE_PEER_ADDRESS=peer0.customs.trackandtrace.com:7056
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.customs.trackandtrace.com:7056
      - CORE_PEER_LOCALMSPID=CustomsMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/peerOrganizations/customs.trackandtrace.com/users/Admin@customs.trackandtrace.com/msp
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/customs.trackandtrace.com/peers/peer0.customs.trackandtrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/customs.trackandtrace.com/peers/peer0.customs.trackandtrace.com/tls:/etc/hyperledger/fabric/tls
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - ./crypto-config/ordererOrganizations/trackandtrace.com/orderers/orderer.trackandtrace.com/msp/tlscacerts:/etc/hyperledger/fabric/orderer
      - ./crypto-config/peerOrganizations/customs.trackandtrace.com/users/Admin@customs.trackandtrace.com/msp:/etc/hyperledger/fabric/crypto-config/peerOrganizations/customs.trackandtrace.com/users/Admin@customs.trackandtrace.com/msp
      - ./customs:/var/hyperledger/fabric/config
      - ./crypto-config/peerOrganizations/customs.trackandtrace.com/peers/peer0.customs.trackandtrace.com/tls:/var/hyperledger/fabric/config/tls
      - ./crypto-config/peerOrganizations/customs.trackandtrace.com/users/Admin@customs.trackandtrace.com/tls:/var/hyperledger/fabric/config/users
      - ./chaincode-java:/etc/hyperledger/fabric/chaincode
    ports:
      - 7056:7056
